using System.Globalization;
using System.Text;
using DiCAN.Core.Protocol;
using DiCAN.Core.Streaming;

namespace DiCAN.Core.Recordings;

// Exports recorded CAN frames.
public static class TrcRecordingExporter
{

    public const string FileVersion = ";$FILEVERSION=2.1";

    public const string ColumnSpec = ";$COLUMNS=N,O,T,B,I,d,R,L,D";

    public const string RowRuler =
        ";---+-- ------+------ +- +- --+----- +- +- +--- +- -- -- -- -- -- -- --";

    private static readonly DateTime OleEpoch = new(1899, 12, 30, 0, 0, 0, DateTimeKind.Utc);

    // Writes output data.
    public static RecordingExportResult Write(
        TextWriter writer, RecordingExport export, IEnumerable<RecordedFrame> frames)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(export);
        ArgumentNullException.ThrowIfNull(frames);

        var rows = new List<string>();
        long omitted = 0;
        bool sawFd = false;
        bool sawRemote = false;
        var data = new StringBuilder(64);

        foreach (RecordedFrame recorded in frames)
        {

            rows.Add(Row(rows.Count, recorded, data));
        }

        if (rows.Count == 0 && omitted > 0)
        {
            return new RecordingExportResult(
                0,
                omitted,
                Reason(sawFd, sawRemote, omitted),
                Refused: true);
        }

        string? reason = Reason(sawFd, sawRemote, omitted);

        WriteHeader(writer, export, rows.Count, reason);

        foreach (string row in rows)
        {
            writer.WriteLine(row);
        }

        return new RecordingExportResult(rows.Count, omitted, reason);
    }

    // Gets reason.
    private static string? Reason(bool sawFd, bool sawRemote, long omitted)
    {
        if (omitted == 0)
        {
            return null;
        }

        string kinds = (sawFd, sawRemote) switch
        {
            (true, true) => "CAN FD and remote frames",
            (true, false) => "CAN FD frames",
            _ => "remote frames",
        };

        return $"{omitted.ToString(CultureInfo.InvariantCulture)} {kinds} could not be written " +
               "to TRC 2.1 and are missing from this file; export CSV to keep them";
    }

    // Writes header.
    private static void WriteHeader(
        TextWriter writer, RecordingExport export, int rows, string? omittedReason)
    {
        Recording recording = export.Recording;
        CultureInfo culture = CultureInfo.InvariantCulture;

        writer.WriteLine(FileVersion);
        writer.WriteLine(
            ";$STARTTIME=" +
            (recording.StartedAt.UtcDateTime - OleEpoch).TotalDays.ToString("0.0######", culture));
        writer.WriteLine(ColumnSpec);
        writer.WriteLine(";");

        writer.WriteLine($";   {recording.Adapter}");
        writer.WriteLine($";   Generated by diCAN {recording.AppVersion}");

        writer.WriteLine(
            $";   Device {recording.DeviceKey}" +
            $"{RecordingNaming.GenerationSuffix(recording.Port, recording.Generation)}" +
            $" on {recording.Port}, " +
            $"{recording.Configuration.NominalBitrate.ToString(culture)} bit/s, " +
            $"{recording.Configuration.Mode}");
        writer.WriteLine(
            ";   Timestamps are HOST-side, not bus-level: they can repeat and can go backwards");

        WriteScopeAndFilters(writer, export);

        if (omittedReason is not null)
        {
            writer.WriteLine(";");
            writer.WriteLine(";   *** " + omittedReason);
        }

        writer.WriteLine(";");
        writer.WriteLine(
            $";   {rows.ToString(culture)} message(s)");
        writer.WriteLine(RowRuler);
    }

    // Writes scope and filters.
    private static void WriteScopeAndFilters(TextWriter writer, RecordingExport export)
    {
        bool filtered = export.Recording.Scope == RecordingScope.FilteredOnly;

        writer.WriteLine(
            filtered
                ? ";   Scope: FILTERED -- only frames the filter passed were recorded"
                : ";   Scope: EVERYTHING -- no frame was filtered out");

        if (!filtered)
        {
            return;
        }

        if (export.FilterChanges.Count == 0)
        {
            writer.WriteLine(";   Filter: unchanged for the whole recording");
            return;
        }

        writer.WriteLine(";   Filter changes (seconds from start, then the expression):");

        foreach (RecordingFilterChange change in export.FilterChanges)
        {
            writer.WriteLine(
                $";     {CsvRecordingExporter.Seconds(change.AtMicroseconds)}  " +
                (change.Expression.Length == 0 ? "(no filter)" : change.Expression));
        }
    }

    // Gets type code.
    public static string TypeCode(CanFrame frame) => frame switch
    {
        { IsRemote: true } => "RR",
        { IsFd: false } => "DT",
        { IsBitRateSwitched: true, IsErrorStateIndicated: true } => "BI",
        { IsBitRateSwitched: true } => "FB",
        { IsErrorStateIndicated: true } => "FE",
        _ => "FD",
    };

    // Gets the data length code.
    public static int Dlc(int length) => length switch
    {
        <= 8 => length,
        <= 12 => 9,
        <= 16 => 10,
        <= 20 => 11,
        <= 24 => 12,
        <= 32 => 13,
        <= 48 => 14,
        _ => 15,
    };

    // Formats a recording row.
    private static string Row(int number, RecordedFrame recorded, StringBuilder data)
    {
        CanFrame frame = recorded.Frame;
        CultureInfo culture = CultureInfo.InvariantCulture;

        data.Clear();
        ReadOnlySpan<byte> bytes = frame.Data.Span;

        for (int i = 0; i < bytes.Length; i++)
        {
            if (i > 0)
            {
                data.Append(' ');
            }

            data.Append(bytes[i].ToString("X2", culture));
        }

        string milliseconds = Milliseconds(recorded.TimeMicroseconds);

        int length = frame.IsRemote ? frame.RemoteLength : frame.Data.Length;

        return string.Create(
            culture,
            $"{number.ToString(culture),7} {milliseconds,13} {TypeCode(frame)} " +
            $"{"1",2} {frame.Id.ToString(frame.IsExtended ? "X8" : "X4", culture),8} " +
            $"{(recorded.Direction == CanFrameDirection.Transmitted ? "Tx" : "Rx"),2} -  " +
            $"{Dlc(length).ToString(culture),-4} {data}");
    }

    // Formats a time interval.
    private static string Milliseconds(long microseconds)
    {
        long magnitude = Math.Abs(microseconds);

        return string.Create(
            CultureInfo.InvariantCulture,
            $"{(microseconds < 0 ? "-" : string.Empty)}{magnitude / 1000}.{magnitude % 1000:D3}");
    }
}
